body:
- type: textarea
  attributes:
    label: Summary
    description: Give a quick description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Let us know how we can replicate the problem. Feel free to include code, error messages, screenshots, or any other detail needed to show us exactly what is happening.
  validations:
    required: true
- type: input
  attributes:
    label: Example
    description: A link to a minimal reproduction or demo deployment is helpful for collaborative debugging.
  validations:
    required: false
